name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo rustc -- -C panic=abort -C link-args=-nostdlib -C link-args=-nostartfiles
    # We cannot use cargo test directly in no_std crates because cargo test links in libtest which in turn links libstd
    # I am thinking about how to do it now
      #- name: Run tests
      #      run: cargo test --verbose
